### ISSUE TITLE
Use Flag Management Issues

### ISSUE THREAD

**Issue by WillPower3309** [InBetweenNames/gentooLTO#660]
Hello, when using `euse` or `flaggie`, two popular use flag management programs, both had issues with make.conf sourcing make.conf.lto with its relative file path, as well as make.conf.lto sourcing make.conf.lto.defines with its relative path. The fix was to change my make.conf and make.conf.lto to `source` using absolute file paths from root. Posting this in case the devs deem it worthy to modify things to be referenced by their absolute paths, as this is a potential issue that could arise for some users

**Comment by telans** [comment]
What were the issues those programs were experiencing? It's a good idea, but I don't have issues myself

**Comment by WillPower3309** [comment]
Both exhibited the error below:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/flaggie", line 25, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.8/site-packages/flaggie/cli.py", line 192, in main
    mkconf = MakeConf(
  File "/usr/lib/python3.8/site-packages/flaggie/makeconf.py", line 537, in __init__
    self.parse(mf, path)
  File "/usr/lib/python3.8/site-packages/flaggie/makeconf.py", line 582, in parse
    self.files[fn] = self.MakeConfFile(fn, path)
  File "/usr/lib/python3.8/site-packages/flaggie/makeconf.py", line 455, in __init__
    f = codecs.open(path, 'r', 'utf8')
  File "/usr/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
NotADirectoryError: [Errno 20] Not a directory: '/etc/portage/make.conf/make.conf.lto'
```

**Comment by WillPower3309** [comment]
Its strange as the last line makes it appear as though it correctly interpreted the file path, but the issue disappears when I change it the the absolute file paths in my make.conf and make.conf.lto

**Comment by jian-lin** [comment]
I have a issue here using `euse`.
```
$ sudo LANG=C euse -p www-client/firefox -E wayland
/etc/portage/make.conf: line 8: make.conf.lto: No such file or directory
Adding "www-client/firefox[wayland]" use flag in "/etc/portage/package.use/firefox"
```

The 8th line of `/etc/portage/make.conf` is `source make.conf.lto`.

**Comment by jian-lin** [comment]
According to [this](https://github.com/mgorny/flaggie/issues/23) issue of `flaggie`, this problem is fixed by [this](https://github.com/mgorny/flaggie/commit/01b8786b9386ed01aa04ac6f1e5b4e429f30d103) commit, which removing the support for `make.conf`.

**Comment by WillPower3309** [comment]
> I have an issue here using `euse`.
> 
> ```
> $ sudo LANG=C euse -p www-client/firefox -E wayland
> /etc/portage/make.conf: line 8: make.conf.lto: No such file or directory
> Adding "www-client/firefox[wayland]" use flag in "/etc/portage/package.use/firefox"
> ```
> 
> The 8th line of `/etc/portage/make.conf` is `source make.conf.lto`.

I had the same issue on euse prior to using absolute paths

**Comment by kartebi** [comment]
ufed also breaks and solution is to use absolute path both in make.conf and make.conf.lto

**Comment by WillPower3309** [comment]
@telans should I submit a pull request for this? Just wanna make sure its a wanted feature as I understand absolute paths are inherently less flexible

**Comment by telans** [comment]
Are you suggesting to just change the example in the readme? I imagine if anyone has a different sysroot they would pick it up and change it.

**Comment by WillPower3309** [comment]
> Are you suggesting to just change the example in the readme? I imagine if anyone has a different sysroot they would pick it up and change it. Or maybe that wouldn't matter if running from inside a sysroot with relative paths

I would make a note in the readme and change the path in line 74 of `sys-config/ltoize/files/make.conf.lto` to be `/etc/portage/make.conf.lto.defines`, as well as update line 15 of that file to reflect the changes

**Comment by telans** [comment]
Yeah you should submit a PR, sounds like a good change
