### ISSUE TITLE
dev-lang/python-3.6.3-r2 hangs while building with lto

### ISSUE THREAD

**Issue by Althorion** [InBetweenNames/gentooLTO#81]
dev-lang/python-3.6.3-r2 hangs while building with lto on `test_asyncio`, throwing an exception:
https://gist.github.com/8bd43d224a6097cbad7eb062661b6c6a

Important part:
```
0:01:52 load avg: 2.71 [ 25/400] test_asyncio
Executing <Task finished coro=<CoroutineTests.test_async_def_wrapped.<locals>.start() done, defined at /var/tmp/portage/dev-lang/python-3.6.3-r2/work/Python-3.6.3/Lib/test/test_asyncio/test_pep492.py:150> result=None created at /var/tmp/
portage/dev-lang/python-3.6.3-r2/work/Python-3.6.3/Lib/asyncio/base_events.py:446> took 0.419 seconds
Exception in thread Thread-85:
Traceback (most recent call last):
  File "/var/tmp/portage/dev-lang/python-3.6.3-r2/work/Python-3.6.3/Lib/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/var/tmp/portage/dev-lang/python-3.6.3-r2/work/Python-3.6.3/Lib/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/var/tmp/portage/dev-lang/python-3.6.3-r2/work/Python-3.6.3/Lib/test/test_asyncio/test_streams.py", line 776, in server
    sock.bind(('localhost', 0))
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by mid-kid** [comment]
Is your `lo` interface up? That's required when running the rests that require networking. Something like `ifconfig lo up` before the build should work.

**Comment by Althorion** [comment]
It is:
```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 749  bytes 49032 (47.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 749  bytes 49032 (47.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Putting it down and up again changes nothing.

BTW, Python 2.7.14 build without any problems with `lto`.

**Comment by InBetweenNames** [comment]
Does the issue persist if you add `test_asyncio` to your exclusion list?  For example, in the ebuild:

~~~
    if use pgo; then
        emake profile-opt PROFILE_TASK="-m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_asyncio"
    else
        emake CPPFLAGS= CFLAGS= LDFLAGS=
    fi
~~~

**Comment by Althorion** [comment]
No, the problem is strictly with `test_asyncio`. That’s the only test that makes problems, without it Python builds without fail.

**Comment by InBetweenNames** [comment]
I'll add it to the exclusion list then.  If it's causing problems for you, no doubt it is causing problems for others as well.

**Comment by InBetweenNames** [comment]
Fix has been committed.  Let me know if it did the trick.

**Comment by Althorion** [comment]
It did, now it works just fine, thank you.

**Comment by InBetweenNames** [comment]
Excellent, thanks for the followup!
