### ISSUE TITLE
python-3.4: open_wr, unlink denied permissions

### ISSUE THREAD

**Issue by joe4379** [InBetweenNames/gentooLTO#92]
I'm not sure what I should be looking at....

```

6 tests failed again:
    test_compileall test_pyexpat test_runpy test_support
    test_threaded_import test_xmlrpc_net
make[1]: *** [Makefile:501: run_profile_task] Error 1
make[1]: Leaving directory '/var/tmp/portage/portage/dev-lang/python-3.4.6-r2/work/x86_64-pc-linux-gnu'
make: *** [Makefile:491: profile-opt] Error 2
 * ERROR: dev-lang/python-3.4.6-r2::lto-overlay failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/python-3.4.6-r2::lto-overlay'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/python-3.4.6-r2::lto-overlay'`.
 * The complete build log is located at '/var/log/portage/dev-lang:python-3.4.6-r2:20180203-163814.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/portage/dev-lang/python-3.4.6-r2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/portage/dev-lang/python-3.4.6-r2/temp/environment'.
 * Working directory: '/var/tmp/portage/portage/dev-lang/python-3.4.6-r2/work/x86_64-pc-linux-gnu'
 * S: '/var/tmp/portage/portage/dev-lang/python-3.4.6-r2/work/Python-3.4.6'
 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/log/sandbox/sandbox-18419.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /usr/lib64/python3.4/site-packages/__pycache__/test.try
A: /usr/lib64/python3.4/site-packages/__pycache__/test.try
R: /usr/lib64/python3.4/site-packages/__pycache__/test.try
C: ./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_sundry test_curses test_distutils test_imaplib test_import test_asyncio 

F: unlink
S: deny
P: /usr/lib64/python3.4/site-packages/__pycache__/test.try
A: /usr/lib64/python3.4/site-packages/__pycache__/test.try
R: /usr/lib64/python3.4/site-packages/__pycache__/test.try
C: ./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_sundry test_curses test_distutils test_imaplib test_import test_asyncio 

F: open_wr
S: deny
P: /usr/lib64/python3.4/site-packages/__pycache__/test.try
A: /usr/lib64/python3.4/site-packages/__pycache__/test.try
R: /usr/lib64/python3.4/site-packages/__pycache__/test.try
C: ./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_sundry test_curses test_distutils test_imaplib test_import test_asyncio 

F: unlink
S: deny
P: /usr/lib64/python3.4/site-packages/__pycache__/test.try
A: /usr/lib64/python3.4/site-packages/__pycache__/test.try
R: /usr/lib64/python3.4/site-packages/__pycache__/test.try
C: ./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_sundry test_curses test_distutils test_imaplib test_import test_asyncio 
 * --------------------------------------------------------------------------------

>>> Failed to emerge dev-lang/python-3.4.6-r2, Log file:

```

**Comment by InBetweenNames** [comment]
Hi @joe4379, if you exclude these tests:

~~~
test_compileall test_pyexpat test_runpy test_support test_threaded_import test_xmlrpc_net
~~~

directly in the ebuild, does the problem persist?

**Comment by joe4379** [comment]
Hmm... I don't have those anywhere.  Would they be here?  In the src_compile section of /var/db/pkg/dev-lang/python-3.4.6-r2/python-3.4.6-r2.ebuild:

```
if use pgo; then
                emake profile-opt PROFILE_TASK="-m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_sundry test_curses test_distutils test_imaplib test_import test_asyncio"
        else
                emake CPPFLAGS= CFLAGS= LDFLAGS=
        fi


```

**Comment by joe4379** [comment]
i didn't mean to close this issue, hit the wrong button.

**Comment by joe4379** [comment]
This is interesting: "What we tested and decided to use on our own builds after benchmarking at
work was to build with:

make profile-opt PROFILE_TASK="-m test.regrtest -w -uall,-audio -x test_gdb
test_multiprocessing"

https://mail.python.org/pipermail/python-dev/2015-August/141328.html

**Comment by joe4379** [comment]
I added those to the exclusion list (behind the '-x'), and yes it does.  Also, though, it's still running the curses test, which looks like it was already excluded.  I've no idea how ebuilds work.  Should I rebuild the manifest maybe?

```
0:03:08 load avg: 1.39 [ 73/399/1] test_compileall
 * ACCESS DENIED:  open_wr:      /usr/lib64/python3.6/site-packages/__pycache__/test.try
 * ACCESS DENIED:  unlink:       /usr/lib64/python3.6/site-packages/__pycache__/test.try
test test_compileall failed -- Traceback (most recent call last):
  File "/var/tmp/portage/portage/dev-lang/python-3.6.4-r1/work/Python-3.6.4/Lib/test/test_compileall.py", line 234, in setUpClass
    support.unlink(str(path))
  File "/var/tmp/portage/portage/dev-lang/python-3.6.4-r1/work/Python-3.6.4/Lib/test/support/__init__.py", line 397, in unlink
    _unlink(filename)
PermissionError: [Errno 13] Permission denied: '/usr/lib64/python3.6/site-packages/__pycache__/test.try'

0:03:09 load avg: 1.39 [ 74/399/2] test_complex -- test_compileall failed
```
```

0:04:23 load avg: 0.66 [ 86/399/2] test_curses
test test_curses failed -- Traceback (most recent call last):
  File "/var/tmp/portage/portage/dev-lang/python-3.6.4-r1/work/Python-3.6.4/Lib/test/test_curses.py", line 249, in test_module_funcs
    self.stdscr.putwin(f)
_curses.error: putwin() returned ERR

0:04:24 load avg: 0.66 [ 87/399/3] test_datetime -- test_curses failed
```

**Comment by joe4379** [comment]
Yes.  It still seems to be running the tests.  Curses as well, which would seem to already be disabled.  I try and rebuild the manifest and can't; maybe I'm doing it wrong.  This is the same error on 3.6:
```

>>> Source compiled.
 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/log/sandbox/sandbox-19133.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /usr/lib64/python3.6/site-packages/__pycache__/test.try
A: /usr/lib64/python3.6/site-packages/__pycache__/test.try
R: /usr/lib64/python3.6/site-packages/__pycache__/test.try
C: ./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_asyncio test_ctypes 

F: unlink
S: deny
P: /usr/lib64/python3.6/site-packages/__pycache__/test.try
A: /usr/lib64/python3.6/site-packages/__pycache__/test.try
R: /usr/lib64/python3.6/site-packages/__pycache__/test.try
C: ./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_asyncio test_ctypes 

F: open_wr
S: deny
P: /usr/lib64/python3.6/site-packages/__pycache__/test.try
A: /usr/lib64/python3.6/site-packages/__pycache__/test.try
R: /usr/lib64/python3.6/site-packages/__pycache__/test.try
C: ./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_asyncio test_ctypes 

F: unlink
S: deny
P: /usr/lib64/python3.6/site-packages/__pycache__/test.try
A: /usr/lib64/python3.6/site-packages/__pycache__/test.try
R: /usr/lib64/python3.6/site-packages/__pycache__/test.try
C: ./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_asyncio test_ctypes 
 * --------------------------------------------------------------------------------

>>> Failed to emerge dev-lang/python-3.6.4-r1, Log file:

>>>  '/var/log/portage/build/dev-lang/python-3.6.4-r1:20180204-193012.log'
z270 /var/db/pkg/dev-lang/python-3.6.4-r1 # nano python-3.6.4-r1.ebuild
z270 /var/db/pkg/dev-lang/python-3.6.4-r1 # ebuild manifest
usage: Usage: ebuild <ebuild file> <command> [command] ...
ebuild: error: missing required args
z270 /var/db/pkg/dev-lang/python-3.6.4-r1 # ebuild python-3.6.4-r1.ebuild manifest
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/ebuild", line 349, in <module>
    vartree=portage.db[portage.root]['vartree'])
  File "/usr/lib64/python3.6/site-packages/portage/package/ebuild/doebuild.py", line 1097, in doebuild
    return not digestgen(mysettings=mysettings, myportdb=mydbapi)
  File "/usr/lib64/python3.6/site-packages/portage/proxy/objectproxy.py", line 31, in __call__
    return result(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/portage/package/ebuild/digestgen.py", line 45, in digestgen
    for cpv in fetchlist_dict:
  File "/usr/lib64/python3.6/site-packages/portage/dbapi/porttree.py", line 1283, in __iter__
    return iter(self.portdb.cp_list(self.cp, mytree=self.mytree))
TypeError: cp_list() got an unexpected keyword argument 'mytree'
z270 /var/db/pkg/dev-lang/python-3.6.4-r1 # ebuild python-3.6.4-r1.ebuild digest
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/ebuild", line 349, in <module>
    vartree=portage.db[portage.root]['vartree'])
  File "/usr/lib64/python3.6/site-packages/portage/package/ebuild/doebuild.py", line 1101, in doebuild
    return not digestgen(mysettings=mysettings, myportdb=mydbapi)
  File "/usr/lib64/python3.6/site-packages/portage/proxy/objectproxy.py", line 31, in __call__
    return result(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/portage/package/ebuild/digestgen.py", line 45, in digestgen
    for cpv in fetchlist_dict:
  File "/usr/lib64/python3.6/site-packages/portage/dbapi/porttree.py", line 1283, in __iter__
    return iter(self.portdb.cp_list(self.cp, mytree=self.mytree))
TypeError: cp_list() got an unexpected keyword argument 'mytree'
```

**Comment by joe4379** [comment]
sorry, here's my change to the ebuild:
```

if use pgo; then
                emake profile-opt PROFILE_TASK="-m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_asyncio test_ctypes test_compileall test_pyexpat test_runpy test_support test_threaded_import test_xmlrpc_net"
        else

```

**Comment by InBetweenNames** [comment]
Excellent, did that solve the issue for you?  Also, did it solve the other issue you posted as well?  I can walk you through making a pull request so that you receive credit for your contribution.

**Comment by joe4379** [comment]
No, the problem persists.  The tests are still running - that's my second try, above.

**Comment by InBetweenNames** [comment]
Does the ebuild build fine without PGO?

**Comment by joe4379** [comment]
Yes

**Comment by InBetweenNames** [comment]
~~~
./python -m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_asyncio test_ctypes 
~~~

From your second try, it appears that the tests `test_compileall test_pyexpat test_runpy test_support test_threaded_import test_xmlrpc_net` weren't actually excluded, despite you modifying the ebuild as you have shown.  I suspect the wrong ebuild is being built. Can you try the following:

~~~
cd /path/to/modified/ebuild
ebuild modified-ebuild.ebuild clean
ebuild modified-ebuild.ebuild merge
~~~

You should not need to regenerate any manifests to do this as we use thin manifests in this repo, and the sourced files are identical.

**Comment by joe4379** [comment]
oh geez I was using emerge.  I'll try ebuild merge when I'm local tonight.

**Comment by joe4379** [comment]
I was editing the ebuild in /var/db/pkg.  It looks to be building correctly.

**Comment by joe4379** [comment]
Nice, 3.6 installed with pgo.

**Comment by joe4379** [comment]
3.4 and 3.5 are good too now.  Thanks!

**Comment by InBetweenNames** [comment]
Could you make a PR with your changes?

**Comment by joe4379** [comment]
I can try... I've only forked the kernel, and never pushed changes.  So, I forked and cloned the repo, and changed the ebuild in my /usr/src/gentooLTOjoe.  So... now what?  :)  Thanks

**Comment by joe4379** [comment]
Done!  For 3.6.  I'll do the others next.  Woo!

**Comment by Necryotiks** [comment]
Im having the same errors as OP used to have. These tests are still running even though the commit was pushed. Is there any addition way to disable them?

**Comment by InBetweenNames** [comment]
Hi @Necryotiks , are you running the latest GentooLTO?  Do a quick `git pull` in the `lto-overlay` on your system just to be sure.  If the problem persists, could you post a complete log here?

**Comment by Necryotiks** [comment]
Huh, so apparently it worked after I manually synced the repo with layman -S. Before, I had used eix-sync so i guess that makes a difference. Thank you.

**Comment by InBetweenNames** [comment]
No problem -- I will mark this as resolved
